### ISSUE TITLE
Timezone issue on Windows

### ISSUE THREAD

**Issue by hazem-osama** [adamdotai/date-io#1]
When running `yarn test` on windows, the OS timezone is converted to UTC, so after finishing the test the developer needs to set the timezone back to his original timezone.

We need to figure out a way to handle the timezone on windows without changing the OS timezone.

**Comment by menna-mostafa** [comment]
@hazem-osama oh, the tests change the timezone of the device to the UTC?

**Comment by hazem-osama** [comment]
Yup 😵, only on windows though 😅

**Comment by menna-mostafa** [comment]
Is there a reported issue on the library with that?

**Comment by hazem-osama** [comment]
> Is there a reported issue on the library with that?

nope, the problem is in node, not the library
