### ISSUE TITLE
add `getTodaysDateFromTime` function

### ISSUE THREAD

**Issue by hazem-osama** [adamdotai/date-io#4]
The function will take a time string (`12:30 PM`) and it will turn into a date object with today's date and the passed time

**Comment by menna-mostafa** [comment]
@hazem-osama May u elaborate, u mean if I passed a time it change it to date time with today date?

**Comment by hazem-osama** [comment]
It was mainly for the `TimeInput`, the user only inputs time (`12:30 PM`) but we need to have it as a date object
